Feature/65-Fix-tests-Dialogue-Manager
iai-group/MovieBot pull request #148
Opened 2023-03-20 20:46 UTC by IKostric

2023-03-24 15:12 UTC, WerLaj approved these changes
LGTM but I checked `_get_elicit_or_recommend_dialogue_acts` only briefly. I found it really difficult to understand the logic inside.

2023-03-27 20:14 UTC, vinaysetty requested changes
Looks mostly good just nits and one function with lots of conditions, see if it can be simplieifed.

2023-04-13 11:19 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_act.py
>          """Removes constraint from the list of parameters."""
Done

2023-04-13 11:21 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +            dialogue_state: Current dialogue state.
Done

2023-04-13 11:23 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +    def _get_elicit_dialogue_act(
done

2023-04-13 11:23 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +        if user_intents.intersection(
Done

2023-04-13 11:28 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +            dialogue_state: Current dialogue state.
Done

2023-04-13 21:07 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +            return [
It is for consistency with other functions.

2023-04-13 21:09 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +        """Generates the elicit or recommend dialogue acts if applicable.
I haven't looked too closely into dialogue flow. The focus in this PR is on refactoring the `next_action` function. The functionality stayed the same. We will address the flow in future PRs.

2023-04-13 21:11 UTC, IKostric commented on moviebot/dialogue_manager/dialogue_policy.py
> +        agent_dacts = []
Refactored further.

2023-04-13 21:26 UTC, IKostric commented
This PR deals with extending the dialogue manager tests and refactoring some complex functions. The dialogue flow is left unchanged.

2023-04-14 06:24 UTC, merged