Option for shorter button text in Telegram
iai-group/moviebot pull request #43
Opened 2021-05-11 20:23 UTC by fseimb

Added short button text as part of the messenger mode option. If messenger mode is set to true, Telegram will display fewer buttons with shorter button text.

2021-05-12 08:36 UTC, kbalog requested changes

2021-05-12 08:36 UTC, kbalog commented on config/bot_token.yaml
> +MESSENGER_TOKEN: "EAAF5ZA8L6hnUBAJjhWUh5g0sk7ZB6Ub9yKuEzk6Ael2Ym5oX2JpTSJHT0rk9WAVGNw92ZB3pzkNMfw5PnTZA7SpVqa0fTLAwWZCQvK4I0npb1ZB9zIqZAKqRuUQheIVglOlqw4mZCP3ZApvVKxYsAymDCn1ZCK7iqsTp92CHYBGwbGZA57B1
These should not be pushed

2021-05-12 08:36 UTC, kbalog commented on config/bot_token.yaml
> +MESSENGER_VERIFY_TOKEN: "bonobo"
This should not be pushed

2021-05-12 08:36 UTC, kbalog commented on moviebot/controller/server.py
> +URL = "https://025d8e8dc5c6.ngrok.io/" # Webhook url
Move this to config file or pass it as a command line argument

2022-12-02 10:40 UTC, IKostric commented
@kbalog Should this PR be followed up on or closed?

2022-12-02 12:51 UTC, kbalog commented
Moving the server address and tokens to a config file should be done. Not sure the messenger controller and other changes in this PR are needed.

2022-12-02 22:34 UTC, closed without merging